config/routes.rb
Rails.application.routes.draw do
  resources :leads
  get 'ad', to: "ad#show"
  get 'calculate', to: "visitors#calculate"
  get 'inquire', to: "leads#new"

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'visitors#index'
  devise_for :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :access, :rails_admin   # grant access to rails_admin
    can :dashboard              # grant access to the dashboard
    can :manage, :all

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
end

app/models/installation.rb
class Installation < ActiveRecord::Base
end

app/models/lead.rb
class Lead < ActiveRecord::Base
end

app/models/quote.rb
class Quote < ActiveRecord::Base
end

app/models/report.rb
class Report < ActiveRecord::Base
end

app/models/service_request.rb
class ServiceRequest < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/ad_controller.rb
class AdController < ApplicationController
  layout 'blank'
  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :set_lead, only: [:show, :edit, :update, :destroy]

  # GET /leads
  # GET /leads.json
  def index
    @leads = Lead.all
  end

  # GET /leads/1
  # GET /leads/1.json
  def show
  end

  # GET /leads/new
  def new
    @lead = Lead.new
  end

  # GET /leads/1/edit
  def edit
  end

  # POST /leads
  # POST /leads.json
  def create
    @lead = Lead.new(lead_params)

    respond_to do |format|
      if @lead.save
        format.html { redirect_to @lead, notice: 'Lead was successfully created.' }
        format.json { render :show, status: :created, location: @lead }
      else
        format.html { render :new }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leads/1
  # PATCH/PUT /leads/1.json
  def update
    respond_to do |format|
      if @lead.update(lead_params)
        format.html { redirect_to @lead, notice: 'Lead was successfully updated.' }
        format.json { render :show, status: :ok, location: @lead }
      else
        format.html { render :edit }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leads/1
  # DELETE /leads/1.json
  def destroy
    @lead.destroy
    respond_to do |format|
      format.html { redirect_to leads_url, notice: 'Lead was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lead
      @lead = Lead.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lead_params
      params.require(:lead).permit(:name, :email, :phone, :location, :lat, :lng, :bill, :load, :area, :area_type)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  layout "blank"
  def calculate
    @lead = Lead.new
    @lat = params[:lat]
    @lng = params[:lng]
  end
end

app/helpers/ad_helper.rb
module AdHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/views/ad/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="ad-box">
        <div class="text-upper-initial">
          Did you know you can save upto
          <div class="amount">
            70%
          </div>
          on your electricity bill?
        </div>

        <div class="btn btn-xl btn-default trigger">
          How?
        </div>

        <div class="text-upper">
          You could save upto
          <div class="amount">
            Rs. 10000
          </div>
          on your electricity bill by switching to solar!
          <small><br>Based on your location and general assumptions.</small>
        </div>

        <a href="/calculate" class="btn btn-link the-link">
          <div class="btn btn-xl btn-default cta">
            Find out how
          </div>
        </a>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).on('ready',function(){
    $(".trigger").click(function(){
      $(".trigger").hide();
      $(".text-upper-initial").hide();
      $(".text-upper").show();
      $(".cta").show();
      var startPos;
      var geoSuccess = function(position) {
        startPos = position;
        lat = startPos.coords.latitude;
        lng = startPos.coords.longitude;
        link = "/calculate?lat="+lat+"&lng="+lng;
        $(".the-link").attr("href",link);

//        document.getElementById('startLat').innerHTML = startPos.coords.latitude;
//        document.getElementById('startLon').innerHTML = startPos.coords.longitude;
      };
      navigator.geolocation.getCurrentPosition(geoSuccess);
    });
  });
</script>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Enengygrade" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Enengygrade" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/blank.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Enengygrade" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Enengygrade" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/leads/_form.html.erb
<%= simple_form_for(@lead) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :phone %>
    <%= f.input :location %>
    <%= f.input :lat %>
    <%= f.input :lng %>
    <%= f.input :bill %>
    <%= f.input :load %>
    <%= f.input :area %>
    <%= f.input :area_type %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/leads/edit.html.erb
<h1>Editing Lead</h1>

<%= render 'form' %>

<%= link_to 'Show', @lead %> |
<%= link_to 'Back', leads_path %>

app/views/leads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Leads</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Location</th>
      <th>Lat</th>
      <th>Lng</th>
      <th>Bill</th>
      <th>Load</th>
      <th>Area</th>
      <th>Area type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leads.each do |lead| %>
      <tr>
        <td><%= lead.name %></td>
        <td><%= lead.email %></td>
        <td><%= lead.phone %></td>
        <td><%= lead.location %></td>
        <td><%= lead.lat %></td>
        <td><%= lead.lng %></td>
        <td><%= lead.bill %></td>
        <td><%= lead.load %></td>
        <td><%= lead.area %></td>
        <td><%= lead.area_type %></td>
        <td><%= link_to 'Show', lead %></td>
        <td><%= link_to 'Edit', edit_lead_path(lead) %></td>
        <td><%= link_to 'Destroy', lead, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lead', new_lead_path %>

app/views/leads/new.html.erb
<h1>New Lead</h1>

<%= render 'form' %>

<%= link_to 'Back', leads_path %>

app/views/leads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lead.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @lead.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @lead.phone %>
</p>

<p>
  <strong>Location:</strong>
  <%= @lead.location %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @lead.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @lead.lng %>
</p>

<p>
  <strong>Bill:</strong>
  <%= @lead.bill %>
</p>

<p>
  <strong>Load:</strong>
  <%= @lead.load %>
</p>

<p>
  <strong>Area:</strong>
  <%= @lead.area %>
</p>

<p>
  <strong>Area type:</strong>
  <%= @lead.area_type %>
</p>

<%= link_to 'Edit', edit_lead_path(@lead) %> |
<%= link_to 'Back', leads_path %>

app/views/visitors/calculate.html.erb
<div class="container">
  <div class="row" style="padding-top: 50px;">

    <form action="" class="form-inline calculate-form">
      <div class="col-xs-2 col-md-2">
        <label for="location" class="control-label">Location</label>
        <input name="area" type="text" value='' class="form-control" id="location" placeholder="Okhla, Delhi">
      </div>
      <div class="form-group col-xs-2 col-md-2">
        <label for="bill" class="control-label">Monthly Bill (Rs.)</label>
        <input name="bill" type="text" value='' class="form-control" id="bill" placeholder="10000">
      </div>
      <div class="form-group col-xs-2 col-md-2">
        <label for="load" class="control-label">Load (kW)</label>
        <input name="load" type="text" value='' class="form-control" id="load" placeholder="5">
      </div>
      <div class="form-group col-xs-2 col-md-2">
        <label for="area" class="control-label">Roof Area (sq.ft.)</label>
        <input name="area" type="text" value='' class="form-control" id="area" placeholder="1000">
      </div>
      <div class="form-group col-xs-2 col-md-2">
        <label for="type" class="control-label">Connection Type</label>
        <select name="type" id="type" class="form-control" style="width: 100%">
          <option selected value="res">Residential</option>
          <option value="ind">Industrial</option>
          <option value="com">Commercial</option>
        </select>
      </div>
      <div class="form-group col-xs-2 col-md-2">
        <button  class="btn btn-primary form-control" id="calculate" style="margin-top: 18px;">Calculate</button>
      </div>
    </form>
  </div>
  <div class="row" id="after-calc" style="display: none;">
    <img src="/1.png" alt=""  style="padding: 50px;width: 100%;max-width:100%;height:auto;">
    <br><br>
    <h1>Interested in getting setup? Fill in the details below and we will reach out to you</h1>
    <form class="form-horizontal" id="lead-form">
      <div class="form-group">
        <label class="control-label col-sm-2" for="pwd">Name:</label>
        <div class="col-sm-10">
          <input type="text" class="form-control" id="name" placeholder="Doctor Strange">
        </div>
      </div>
      <div class="form-group">
        <label class="control-label col-sm-2" for="email">Email:</label>
        <div class="col-sm-10">
          <input type="email" class="form-control" id="email" placeholder="john@doe.com">
        </div>
      </div>
      <div class="form-group">
        <label class="control-label col-sm-2" for="pwd">Contact Number:</label>
        <div class="col-sm-10">
          <input type="number" class="form-control" id="contact" placeholder="9876543210">
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-default">Submit</button>
        </div>
      </div>
    </form>
    <div class="after-lead" style="display: none;">
      <br><br>
      <h1>Thank you, you request have been recorded and one of our agents will get back to you shortly.</h1>
    </div>
  </div>
</div>
<script type="text/javascript" charset="utf-8">
  function initMap(){
    lat = <%= @lat %>;
    lng = <%= @lng %>;
    var latlng = {lat: parseFloat(lat), lng: parseFloat(lng)};
    var geocoder = new google.maps.Geocoder;
    geocoder.geocode({'location': latlng}, function(results, status) {
      if (status === 'OK') {
        if (results[1]) {
          addr = results[1].formatted_address;
          $("form.calculate-form input#location").val(addr);
        } else {
          window.alert('No results found');
        }
      } else {
        window.alert('Geocoder failed due to: ' + status);
      }
    });

  }
  $(document).on('ready',function(){
    $("form.calculate-form").submit(function(e){
      e.preventDefault();
      $("#after-calc").show();
    });
    $("#lead-form").submit(function(e){
      e.preventDefault();
      $(".after-lead").show();
      data = {
        "lead": {
          name: $("form#lead-form input#name").val(),
          email: $("form#lead-form input#email").val(),
          phone: $("form#lead-form input#contact").val(),
          location: $("form.calculate-form input#location").val(),
          lat: <%= @lat %>,
          lng: <%= @lng %>,
          bill: $("form.calculate-form input#bill").val(),
          load: $("form.calculate-form input#load").val(),
          area: $("form.calculate-form input#area").val(),
          area_type: $("form.calculate-form select#type :selected").text()
        }
      }
      $.ajax({
        type: "POST",
        url: "/leads",
        data: data,
        success: function(){
          console.log("Success");
        }
      });
    })
  })
</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDaewk0hcgMCtAQkVfeBnCtiUTbYRXEJkw&callback=initMap">
</script>

app/views/visitors/index.html.erb
<!-- Page Content -->
<div class="container">

    <!-- Heading Row -->
    <div class="row">
        <div class="col-md-8">
            <img class="img-responsive img-rounded" src="http://placehold.it/900x350" alt="">
        </div>
        <!-- /.col-md-8 -->
        <div class="col-md-4">
            <h1>Business Name or Tagline</h1>
            <p>This is a template that is great for small businesses. It doesn't have too much fancy flare to it, but it makes a great use of the standard Bootstrap core components. Feel free to use this template for any project you want!</p>
            <a class="btn btn-primary btn-lg" href="#">Call to Action!</a>
        </div>
        <!-- /.col-md-4 -->
    </div>
    <!-- /.row -->

    <hr>

    <!-- Call to Action Well -->
    <div class="row">
        <div class="col-lg-12">
            <div class="well text-center">
                This is a well that is a great spot for a business tagline or phone number for easy access!
            </div>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->

    <!-- Content Row -->
    <div class="row">
        <div class="col-md-4">
            <h2>Heading 1</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe rem nisi accusamus error velit animi non ipsa placeat. Recusandae, suscipit, soluta quibusdam accusamus a veniam quaerat eveniet eligendi dolor consectetur.</p>
            <a class="btn btn-default" href="#">More Info</a>
        </div>
        <!-- /.col-md-4 -->
        <div class="col-md-4">
            <h2>Heading 2</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe rem nisi accusamus error velit animi non ipsa placeat. Recusandae, suscipit, soluta quibusdam accusamus a veniam quaerat eveniet eligendi dolor consectetur.</p>
            <a class="btn btn-default" href="#">More Info</a>
        </div>
        <!-- /.col-md-4 -->
        <div class="col-md-4">
            <h2>Heading 3</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe rem nisi accusamus error velit animi non ipsa placeat. Recusandae, suscipit, soluta quibusdam accusamus a veniam quaerat eveniet eligendi dolor consectetur.</p>
            <a class="btn btn-default" href="#">More Info</a>
        </div>
        <!-- /.col-md-4 -->
    </div>
    <!-- /.row -->

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Your Website 2014</p>
            </div>
        </div>
    </footer>

</div>
<!-- /.container -->